### ISSUE TITLE
branching options 

### ISSUE THREAD

**Issue by TowelSniffer** [zeFresk/deep-position-analysis#3]
Hi, cool program, I was wondering if as oppose to picking the top-PV moves, this could be set to choose moves based on a centipawn ranking. I was hoping to use this to calculate all the moves that lead to the shortest possible mate in a position.

**Comment by zeFresk** [comment]
Hello and thank you for submitting an issue :)

I'm not sure I understand what you would like to do but I think you can do what with PV-expression and Threshold-expression that I added a while back but never documented (...).

For example, if you would like to pick the 2 best white moves that are above -100 centipawns and the best move black can play you could try : 
> --pv 2W1B --threshold 100B

If you mean that instead of following the best move given by the engine we should follow the one with the highest score, I could add that, but because of how engines work, the second-best move can have a better score temporarily, but it should still be worse than the top PV if you let the engine think a little more.

In my analysis, given enough time to calculate, the first move will stabilize and its score will always be the highest one.

**Comment by TowelSniffer** [comment]
Hi mate, thanks for your help, I wouldn't call it an issue but I will try to clarify what I was looking for.

say we have a position: 
![image](https://user-images.githubusercontent.com/52064198/83141597-ddf60980-a0e7-11ea-910e-e23e2b16f9ff.png)

this is a forced mate in 6 but there are lots of lines to take for a mate in 6. On fritz deep position analysis, if I set the centipawn cutoff to 0, I found it would include any line that was mate in 6 while ignoring longer lines, say mate in 7. I was hoping that if I set the centipawn threshold to 0 on this program it would behave the same way but it doesn't seem to. 

Just to add, the problem I have with just using fritz is that it limits branching to 4 moves deep which is a bit annoying. 

As for why I want this, I make flashcards out of my game for a program called Anki. 

![temp](https://user-images.githubusercontent.com/52064198/83143473-ebac8e80-a0e9-11ea-9aa9-19285e4c04a6.gif)

**Comment by zeFresk** [comment]
Ok, now I understand the problem.
My --threshold option is only an absolute threshold, it doesn't compare moves with each other.
That would indeed be a good feature to add!

I have more time right now, and since it is not that hard to implement I will try to add it soon :)

**Comment by TowelSniffer** [comment]
You're a legend mate :)

**Comment by zeFresk** [comment]
Hello, I added a --cutoff option which should do what you wanted.
In my tests, it seemed to works fine with checkmates but I would be glad if you could confirm it.

Thank you :)
c85b2f070d196900b69b7e56104be0b825374a7e

**Comment by TowelSniffer** [comment]
that works really well, will definitely use this a lot so if I run into any issues ill let you know. As I use this you make puzzles, it would be nice to only allow branching for a certain colour. would this be doable?

**Comment by TowelSniffer** [comment]
So interestingly for me, I found a weird issue. 

if you have two lines say a mate in 4 and a mate in two, then the cutoff option removes the mate in 4, however, if the mate is one above, so a mate in three, then the line is included. 


so a sample output:

[Event "?"]
[Site "?"]
[Date "2020.06.04"]
[Round "?"]
[White "White"]
[Black "Black"]
[Result "*"]
[FEN "8/2q3k1/7p/5pp1/3p4/7P/5rP1/6K1 b - - 1 40"]
[SetUp "1"]

{ Deep analysis start after that node } 40... Qg3 { -M2 } ( 40... Qf4 { -M3 } 41. g3 { -M2 } 41... Qxg3+ { -M2 } ( 41... Rf1+ { -M2 } 42. Kh2 { -M1 } ( 42. Kg2 { -M1 } 42... Qf2# { -M1 } ( 42... Qf3+ { -M2 } 43. Kh2 { -M1 } 43... Rh1# { -M1 } ( 43... Qh1# { -M1 } ) ) ) 42... Qd2# { -M1 } ( 42... Qf2# { -M1 } ) ) 42. Kh1 { -M1 } 42... Rf1# { -M1 } ( 42... Rh2# { -M1 } ) ) 41. h4 { -M1 } ( 41. Kh1 { -M1 } 41... Qxg2# { -M1 } ( 41... Rf1# { -M1 } ) ) 41... Qxg2# { -M1 } ( 41... Rxg2+ { -M2 } 42. Kf1 { -M1 } ( 42. Kh1 { -M1 } 42... Rg1# { -M1 } ( 42... Rh2# { -M1 } ) ) 42... Qf2# { -M1 } ( 42... Rg1+ { -M2 } 43. Ke2 { -M1 } 43... Qe3# { -M1 } ( 43... Re1+ { -M2 } 44. Kd2 { -M1 } 44... Qc3# { -M1 } ( 44... Qe3+ { -M2 } 45. Kc2 { -M1 } 45... Qc3# { -M1 } ( 45... Re2+ { -M2 } 46. Kb1 { -M1 } ( 46. Kd1 { -M1 } 46... Qd2# { -M1 } ( 46... Re1+ { -M2 } ) ) 46... Qg1# { -M1 } ( 46... Qb3+ { -M2 } ) ) ) ) ) ) *

you can see 40... Qf4 { -M3 } which should be cutoff

**Comment by zeFresk** [comment]
Thank you very much for testing.

It seems I rushed a bit the cut_off function, I will fix that tomorrow and add a way to set cutoff for each side individually.

**Comment by zeFresk** [comment]
Ok, it took me a bit of time but I think I fixed it.
Also, I introduced 'cutoff expression', which are not yet documented but they work like this:
- cutoff for both sides: `--cutoff 100`
- cutoff only for white: `--cutoff 100W` (B for black, not case-sensitive)
- cutoff until move 10: `--cutoff 100u10`
- cutoff after move 10: `--cutoff 100a10`

You can also combine them `--cutoff 100u2a10W25u8a25B`

**Comment by TowelSniffer** [comment]
That sounds fantastic I'm not at my computer now but will try it later

**Comment by TowelSniffer** [comment]
Hey, mate so I managed to test it out and it works perfectly from what I can see. I think being able to set cutoff for each side is a good feature, but it isn't what I was talking about. What I was suggesting was a feature to allow branching for only one colour. so what I run is 

--cutoff 0 --pv 1W200B 

The result is in a scenario where we have branching for black but not white. This is useful as I use this to create puzzles. 

This does what I want it to do so I don't care either way but having a documented way to disable branching for a chosen colour I think would be a nice addition as my approach seems a little hacky.  

The idea comes from one of the options in fritz Deep Position Analysis

![image](https://user-images.githubusercontent.com/52064198/83924826-72620b00-a77d-11ea-83d5-cdd7cc210630.png)

**Comment by zeFresk** [comment]
Sadly because of how UCI engines work the "hacky" way is the only way to do it unless you create your own engine you can't set MultiPV for only one side... :(

However, it is worth noting that high MultiPV will significantly decrease the strength of AB engines, therefore if you use high MultiPV for long analysis I would suggest using MCTS-based engines such as Leela or Komodo-MCTS.

Also, using I don't know if this is what you want but using `--cutoff 0` will always take the best move unless there are two perfectly equals moves.

If you have other suggestions feel free to post them and I will try to add them!

**Comment by TowelSniffer** [comment]
Thanks for the tip. I was aware of this actually, I often use Leela as I prefer it for analysis and it's stronger than stockfish on my hardware but I found even at high PV, stockfish was better at finding forced mates. 

Though Komodo-MCTS looks interesting
